/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import com.mysql.cj.xdevapi.Result;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus S15
 */
public class ManageEmployee extends javax.swing.JFrame {

    Connection con;
    Statement statement;
    DefaultTableModel model;
    Controller control;

    /**
     * Creates new form Addemployee
     */
    public ManageEmployee() {
        initComponents();
        connectToDatabase();
        model = (DefaultTableModel) tblEmployee.getModel();
        control = new Controller();
        getDatatoTable();
    }

    public void connectToDatabase() {
        try {
            String url = "jdbc:mysql://localhost:3306/mysharedb";
            String userName = "root";
            String password = "";

            con = DriverManager.getConnection(url, userName, password);
            statement = con.createStatement();
        } catch (SQLException sqlEx) {
            JOptionPane.showMessageDialog(rootPane, sqlEx);
        }
    }

    public void getDatatoTable() {  //gets data from the db
        try {
            String query = "SELECT * FROM Employee";

            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                int empID = resultSet.getInt("empID");
                String empName = resultSet.getString("name");
                String NIC = resultSet.getString("NIC");
                String gender = resultSet.getString("gender");
                String address = resultSet.getString("address");
                String password = resultSet.getString("password");
                String telephone = resultSet.getString("telephone");
                double salary = resultSet.getDouble("salary");
                String role = resultSet.getString("Role");

                model.addRow(new Object[]{empID, empName, NIC, gender, address, password, telephone, salary, role});
            }
        } catch (SQLException sqlex) {
            JOptionPane.showMessageDialog(rootPane, sqlex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupManageEmp = new javax.swing.ButtonGroup();
        buttonGroupAddEmployee = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbladdemployee = new javax.swing.JLabel();
        lblEmpname = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        Empnametxt = new javax.swing.JTextField();
        NICtxt = new javax.swing.JTextField();
        Addresstxt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lblsalary1 = new javax.swing.JLabel();
        Salarytxt1 = new javax.swing.JTextField();
        TPTxt1 = new javax.swing.JTextField();
        lblTP1 = new javax.swing.JLabel();
        lblsalary2 = new javax.swing.JLabel();
        rdioWorker = new javax.swing.JRadioButton();
        rdioCashier = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        lblManagerheading = new javax.swing.JLabel();
        lblManagerUserID = new javax.swing.JLabel();
        ManagerEmpname = new javax.swing.JLabel();
        ManagerNIC = new javax.swing.JLabel();
        ManagerGender = new javax.swing.JLabel();
        ManagerAddress = new javax.swing.JLabel();
        Managerpassword = new javax.swing.JLabel();
        ManagerSalary = new javax.swing.JLabel();
        managerEmpnametxt = new javax.swing.JTextField();
        managerNICtxt = new javax.swing.JTextField();
        addressManagertxt = new javax.swing.JTextField();
        managersalarytxt = new javax.swing.JTextField();
        gender1 = new javax.swing.JRadioButton();
        gender2 = new javax.swing.JRadioButton();
        jPasswordField = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        manageTPtxt = new javax.swing.JTextField();
        lblTP = new javax.swing.JLabel();
        Regexit = new javax.swing.JLabel();
        lblManageID = new javax.swing.JLabel();
        lblManagerheading1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbladdemployee.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbladdemployee.setText("Add Employee");

        lblEmpname.setBackground(new java.awt.Color(255, 255, 255));
        lblEmpname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpname.setText("Empname");

        lblNIC.setBackground(new java.awt.Color(51, 51, 51));
        lblNIC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNIC.setText("NIC");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setText("Gender");
        lblGender.setToolTipText("");

        lblAddress.setBackground(new java.awt.Color(51, 51, 51));
        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress.setText("Address");

        lblpassword.setBackground(new java.awt.Color(51, 51, 51));
        lblpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpassword.setText("Password");

        Empnametxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Empnametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Empnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpnametxtActionPerformed(evt);
            }
        });

        NICtxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NICtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        NICtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICtxtActionPerformed(evt);
            }
        });

        Addresstxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Addresstxt.setForeground(new java.awt.Color(51, 51, 51));
        Addresstxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddresstxtActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupAddEmployee.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButton1.setText("M");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupAddEmployee.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButton2.setText("F");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblsalary1.setBackground(new java.awt.Color(51, 51, 51));
        lblsalary1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsalary1.setText("Salary");

        Salarytxt1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Salarytxt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Salarytxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salarytxt1ActionPerformed(evt);
            }
        });

        TPTxt1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TPTxt1.setToolTipText("");
        TPTxt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        TPTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPTxt1ActionPerformed(evt);
            }
        });

        lblTP1.setBackground(new java.awt.Color(51, 51, 51));
        lblTP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTP1.setText("Telephone");

        lblsalary2.setBackground(new java.awt.Color(51, 51, 51));
        lblsalary2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsalary2.setText("Job Role");

        buttonGroup1.add(rdioWorker);
        rdioWorker.setText("Worker");

        buttonGroup1.add(rdioCashier);
        rdioCashier.setText("rdioCashier");
        rdioCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioCashierActionPerformed1(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Update.setBackground(new java.awt.Color(0, 0, 0));
        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Remove.setBackground(new java.awt.Color(0, 0, 0));
        Remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Remove.setForeground(new java.awt.Color(255, 255, 255));
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        lblManagerheading.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblManagerheading.setText("Manage Employee");

        lblManagerUserID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblManagerUserID.setText("UserID");
        lblManagerUserID.setToolTipText("");

        ManagerEmpname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManagerEmpname.setText("Name");

        ManagerNIC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManagerNIC.setText("NIC");

        ManagerGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManagerGender.setText("Gender");
        ManagerGender.setToolTipText("");

        ManagerAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManagerAddress.setText("Address");

        Managerpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Managerpassword.setText("Password");

        ManagerSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManagerSalary.setText("Salary");

        managerEmpnametxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        managerEmpnametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        managerEmpnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        managerNICtxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        managerNICtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        managerNICtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        addressManagertxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addressManagertxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        addressManagertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        managersalarytxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        managersalarytxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        managersalarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        gender1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupManageEmp.add(gender1);
        gender1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        gender1.setText("M");
        gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        gender2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupManageEmp.add(gender2);
        gender2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        gender2.setText("F");
        gender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        tblEmployee.setBackground(new java.awt.Color(204, 204, 204));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPID", "NAME", "NIC", "GENDER", "ADDRESS", "PASSWORD", "TELEPHONE", "SALARY", "Role"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        manageTPtxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        manageTPtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        manageTPtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTPtxtActionPerformed(evt);
            }
        });

        lblTP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTP.setText("Telephone");

        Regexit.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        Regexit.setForeground(new java.awt.Color(255, 255, 255));
        Regexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regexit.setText("X");
        Regexit.setPreferredSize(new java.awt.Dimension(16, 16));
        Regexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegexitMouseClicked(evt);
            }
        });

        lblManageID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblManageID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageID.setText("ID");
        lblManageID.setToolTipText("");
        lblManageID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        lblManageID.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblManageIDAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblManagerheading1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblManagerheading1.setForeground(new java.awt.Color(255, 255, 255));
        lblManagerheading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagerheading1.setText("Go To Dashboard");
        lblManagerheading1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        lblManagerheading1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManagerheading1MouseClicked(evt);
            }
        });

        txtDashboard.setBackground(new java.awt.Color(0, 0, 0));
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setText("To Dashboard");
        txtDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(lblManagerheading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManagerheading1)
                .addGap(114, 114, 114)
                .addComponent(jLabel2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Regexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDashboard)))
                .addGap(10, 10, 10))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTP, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ManagerEmpname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ManagerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ManagerNIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ManagerGender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Managerpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblManagerUserID)
                                    .addComponent(ManagerSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(managersalarytxt)
                                    .addComponent(manageTPtxt)
                                    .addComponent(addressManagertxt)
                                    .addComponent(managerNICtxt)
                                    .addComponent(managerEmpnametxt)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(gender1)
                                        .addGap(37, 37, 37)
                                        .addComponent(gender2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblManageID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Remove, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(97, 97, 97)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerheading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManagerheading1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManagerUserID)
                    .addComponent(lblManageID))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerEmpnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManagerEmpname))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerNICtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManagerNIC))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManagerGender)
                    .addComponent(gender1)
                    .addComponent(gender2))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManagerAddress)
                    .addComponent(addressManagertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Managerpassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageTPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTP))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManagerSalary)
                    .addComponent(managersalarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Regexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDashboard)
                        .addGap(140, 140, 140)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbladdemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblsalary1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpname, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblsalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdioWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdioCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Empnametxt)
                                .addComponent(NICtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Addresstxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jRadioButton1)
                                    .addGap(41, 41, 41)
                                    .addComponent(jRadioButton2))
                                .addComponent(Salarytxt1)
                                .addComponent(TPTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbladdemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Empnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmpname))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NICtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNIC))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTP1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsalary1)
                    .addComponent(Salarytxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsalary2)
                    .addComponent(rdioWorker)
                    .addComponent(rdioCashier))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NICtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NICtxtActionPerformed

    private void AddresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddresstxtActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void EmpnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpnametxtActionPerformed

    private void manageTPtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTPtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageTPtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String empName = Empnametxt.getText();
        String NIC = NICtxt.getText();
        String gender = "";
        String role = "";

        if (jRadioButton1.isSelected()) {
            gender = "M";
        } else if (jRadioButton2.isSelected()) {
            gender = "F";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Select a Gender");
            return; // Exit the method if gender is not selected
        }
        
        if (rdioWorker.isSelected()){
            role = "Worker";
        } else if(rdioCashier.isSelected()){
            role = "Cashier";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Select a Role");
        }

        String address = Addresstxt.getText();
        String password = jPasswordField1.getText();
        String telephone = TPTxt1.getText();
        String salaryText = Salarytxt1.getText();

// Check if any field is empty
        if (empName.isEmpty() || NIC.isEmpty() || address.isEmpty() || password.isEmpty() || telephone.isEmpty() || salaryText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in all fields");
            return; // Exit the method if any field is empty
        }

// Parse salary field
        double salary;
        try {
            salary = Double.parseDouble(salaryText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid salary");
            return; // Exit the method if salary is invalid
        }

// Rest of your code...
//        control.addeEmployee(empName, NIC, gender, address, password, telephone, salary, role);
        JOptionPane.showMessageDialog(rootPane, "Object added");
        try {
            String query = "INSERT INTO employee(name, nic, gender, address, password, telephone, salary, Role) VALUES ('" + empName + "','" + NIC + "','" + gender + "','" + address + "','" + password + "','" + telephone + "','" + salary +"','"+ role +"')";
            statement.executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane, "Record Added");
            model.setRowCount(0);
            getDatatoTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        int empID = Integer.parseInt(lblManageID.getText());
        try {
            String queryDelete = "DELETE FROM Employee WHERE empID = " + empID;
            statement.executeUpdate(queryDelete);
            JOptionPane.showMessageDialog(rootPane, "record deleted");
            model.setRowCount(0);
            getDatatoTable();
        } catch (SQLException exsql) {
            JOptionPane.showMessageDialog(rootPane, exsql);
        }
        lblManageID.setText("");
        managerEmpnametxt.setText("");
        managerNICtxt.setText("");
        addressManagertxt.setText("");
        jPasswordField.setText("");
        manageTPtxt.setText("");
        managersalarytxt.setText("");

        buttonGroupManageEmp.clearSelection();
    }//GEN-LAST:event_RemoveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
// TODO add your handling code here:
        int empID;
        try {
            empID = Integer.parseInt(lblManageID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid employee ID");
            return; // Exit the method if employee ID is invalid
        }

        String empName = managerEmpnametxt.getText();
        String NIC = managerNICtxt.getText();
        String gender = "";

        if (gender1.isSelected()) {
            gender = "M";
        } else if (gender2.isSelected()) {
            gender = "F";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select a Gender");
            return; // Exit the method if gender is not selected
        }

        String address = addressManagertxt.getText();
        String password = jPasswordField.getText();
        String TP = manageTPtxt.getText();
        String salaryText = managersalarytxt.getText();

// Check if any field is empty
        if (empName.isEmpty() || NIC.isEmpty() || address.isEmpty() || password.isEmpty() || TP.isEmpty() || salaryText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in all fields");
            return; // Exit the method if any field is empty
        }

// Parse salary field
        double salary;
        try {
            salary = Double.parseDouble(salaryText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid salary");
            return; // Exit the method if salary is invalid
        }

        try {
            String queryUpdate = "UPDATE Employee SET name = '" + empName + "', NIC = '" + NIC + "', gender = '" + gender + "', address = '" + address + "', password = '" + password + "', telephone = '" + TP + "', salary = " + salary + " WHERE empID = " + empID;
            statement.executeUpdate(queryUpdate);
            JOptionPane.showMessageDialog(rootPane, "Record updated");
            model.setRowCount(0);
            getDatatoTable();
        } catch (SQLException exsql) {
            JOptionPane.showMessageDialog(rootPane, exsql);
        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void Salarytxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salarytxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salarytxt1ActionPerformed

    private void TPTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPTxt1ActionPerformed

    private void RegexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegexitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_RegexitMouseClicked

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        //takes the values in the table to text fields
        int selectedRow = tblEmployee.getSelectedRow();
//        model = (DefaultTableModel) tblEmployee.getModel();

        lblManageID.setText(model.getValueAt(selectedRow, 0).toString());
        managerEmpnametxt.setText(model.getValueAt(selectedRow, 1).toString());
        managerNICtxt.setText(model.getValueAt(selectedRow, 2).toString());

        String gender = model.getValueAt(selectedRow, 3).toString();
        if (gender.equalsIgnoreCase("M")) {
            gender1.setSelected(true);
        } else if (gender.equalsIgnoreCase("F")) {
            gender2.setSelected(true);
        }

        addressManagertxt.setText(model.getValueAt(selectedRow, 4).toString());
        jPasswordField.setText(model.getValueAt(selectedRow, 5).toString());
        manageTPtxt.setText(model.getValueAt(selectedRow, 6).toString());
        managersalarytxt.setText(model.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblManagerheading1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagerheading1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_lblManagerheading1MouseClicked

    private void lblManageIDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblManageIDAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblManageIDAncestorAdded

    private void rdioCashierActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioCashierActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_rdioCashierActionPerformed1

    private void txtDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDashboardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_txtDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JTextField Empnametxt;
    private javax.swing.JLabel ManagerAddress;
    private javax.swing.JLabel ManagerEmpname;
    private javax.swing.JLabel ManagerGender;
    private javax.swing.JLabel ManagerNIC;
    private javax.swing.JLabel ManagerSalary;
    private javax.swing.JLabel Managerpassword;
    private javax.swing.JTextField NICtxt;
    private javax.swing.JLabel Regexit;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField Salarytxt1;
    private javax.swing.JTextField TPTxt1;
    private javax.swing.JButton Update;
    private javax.swing.JTextField addressManagertxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupAddEmployee;
    private javax.swing.ButtonGroup buttonGroupManageEmp;
    private javax.swing.JRadioButton gender1;
    private javax.swing.JRadioButton gender2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmpname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblManageID;
    private javax.swing.JLabel lblManagerUserID;
    private javax.swing.JLabel lblManagerheading;
    private javax.swing.JLabel lblManagerheading1;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblTP;
    private javax.swing.JLabel lblTP1;
    private javax.swing.JLabel lbladdemployee;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblsalary1;
    private javax.swing.JLabel lblsalary2;
    private javax.swing.JTextField manageTPtxt;
    private javax.swing.JTextField managerEmpnametxt;
    private javax.swing.JTextField managerNICtxt;
    private javax.swing.JTextField managersalarytxt;
    private javax.swing.JRadioButton rdioCashier;
    private javax.swing.JRadioButton rdioWorker;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JButton txtDashboard;
    // End of variables declaration//GEN-END:variables
}
