/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author justo
 */
public class UpdateOrderRegistory extends javax.swing.JFrame {

    Date d;
    SimpleDateFormat sdf;
    DefaultTableModel model;
    Connection con;
    Statement statement;
    OrderController orderCon;

    /**
     * Creates new form ordeRegistery
     */
    public UpdateOrderRegistory() {
        initComponents();
        showDate();
        model = (DefaultTableModel) tblReg.getModel();
        orderCon = new OrderController();
        connectToDatabase();
        fetchDataFromDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void showDate() {
        d = new Date();
        sdf = new SimpleDateFormat("dd-MM-yyyy");
        lblDate.setText(sdf.format(d));

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat dd = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(dd.format(d));
            }
        }).start();
    }

    public void connectToDatabase() {
        try {
            String url = "jdbc:mysql://localhost:3306/mysharedb";
            String userName = "root";
            String password = "";

            con = DriverManager.getConnection(url, userName, password);
            statement = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    public void fetchDataFromDB() {
        // Retrieve remaining data and add it to the DefaultTableModel
        try {

            String query = "SELECT * FROM orders";
            ResultSet resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
                // Retrieve data from the result set
                int customerId = resultSet.getInt("OrderID");
                String customerName = resultSet.getString("customerName");
                String customerTelephone = resultSet.getString("customerTelephone");
                String customerEmail = resultSet.getString("customerEmail");
                String employeeId = resultSet.getString("employeeId");
                String adObjective = resultSet.getString("adObjective");
                String adTargetAudience = resultSet.getString("adTargetAudience");
                String startDate = resultSet.getString("startDate");
                String endDate = resultSet.getString("endDate");
                String bannerSize = resultSet.getString("bannerSize");
                int quantity = resultSet.getInt("quantity");
                String bannerDescription = resultSet.getString("bannerDescription");
                String artworkType = resultSet.getString("artworkType");
                String artworkDescription = resultSet.getString("artworkDescription");
                double totalPrice = resultSet.getDouble("totalPrice");

                // Add data to the DefaultTableModel
                model.addRow(new Object[]{customerId, customerName, customerTelephone, customerEmail, employeeId, adObjective,
                    adTargetAudience, startDate, endDate, bannerSize, quantity, bannerDescription, artworkType,
                    artworkDescription, totalPrice});
            }

            // Close the ResultSet
            resultSet.close();
        } catch (SQLException sqlex) {
            JOptionPane.showMessageDialog(rootPane, sqlex);
        }
    }

    public static void newOrder(String customerName, String customerTelephone, String customerEmail, int employeeId,
            String adObjective, String adTargetAudience, int startDate, int endDate,
            String bannerSize, int quantity, String bannerDescription, String artworkType,
            String artworkDescription) {

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblheading = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        lblTele1 = new javax.swing.JLabel();
        txtTele1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblemp1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReg = new javax.swing.JTable();
        lblExit = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        pneAdvertisement = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbObjAdv = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTargeAudince = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        strtMonth = new com.toedter.calendar.JMonthChooser();
        txtStrtDat = new javax.swing.JTextField();
        txtEndDay = new javax.swing.JTextField();
        endMonth = new com.toedter.calendar.JMonthChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmdBannerSize = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtBannerDesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        spinnerQuantityBanner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdioGraphic1 = new javax.swing.JRadioButton();
        rdioMotion1 = new javax.swing.JRadioButton();
        rdioIllus1 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArtworkDesc1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblheading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblheading.setText("Manager Order Registery(Cashier)");

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLogout.setIcon(new javax.swing.ImageIcon("D:\\oop project finale\\MyShare-G3 - Finalized\\images\\logout.png")); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName1.setText("Name:");

        txtName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        lblTele1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTele1.setText("Telephone:");

        txtTele1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTele1ActionPerformed(evt);
            }
        });

        lblEmail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail1.setText("Email:");

        txtEmail1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblemp1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblemp1.setText("Total");
        lblemp1.setToolTipText("");

        lblTotal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal1.setText("____________");
        lblTotal1.setToolTipText("");

        btnRemove.setBackground(new java.awt.Color(0, 0, 0));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblName3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName3.setText("ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTele1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblEmail1)
                                    .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTele1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(107, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(lblName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName1))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTele1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTele1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal1)
                    .addComponent(lblemp1))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        tblReg.setAutoCreateRowSorter(true);
        tblReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customerId", "customerName", "customerTelephone", "customerEmail", "employeeId", "adObjective", "adTargetAudience", "startDate", "endDate", "bannerSize", "quantity", "bannerDescription", "artworkType", "artworkDescription", "totalPrice"
            }
        ));
        tblReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblReg);

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Time");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");

        pneAdvertisement.setBackground(new java.awt.Color(255, 255, 255));
        pneAdvertisement.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Objective");

        cmbObjAdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Awareness", "Marketing", "Charity" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("<html>Target  <br> Audience</html>");

        txtTargeAudince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTargeAudinceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Start Date");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Advertisements");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("end Date");

        javax.swing.GroupLayout pneAdvertisementLayout = new javax.swing.GroupLayout(pneAdvertisement);
        pneAdvertisement.setLayout(pneAdvertisementLayout);
        pneAdvertisementLayout.setHorizontalGroup(
            pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pneAdvertisementLayout.createSequentialGroup()
                .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pneAdvertisementLayout.createSequentialGroup()
                        .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pneAdvertisementLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pneAdvertisementLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStrtDat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(strtMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pneAdvertisementLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbObjAdv, 0, 168, Short.MAX_VALUE)
                            .addComponent(txtTargeAudince))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pneAdvertisementLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(93, 93, 93))
        );
        pneAdvertisementLayout.setVerticalGroup(
            pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pneAdvertisementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbObjAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pneAdvertisementLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtTargeAudince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtStrtDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(strtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pneAdvertisementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("<html> Banner <br> Size </html>");

        cmdBannerSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1024*780", "1280*1980", "540*480" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Description");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Quantity");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Banners");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdBannerSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBannerDesc)
                            .addComponent(spinnerQuantityBanner)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdBannerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spinnerQuantityBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBannerDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Artworks");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("<html>Artwork <br> Type </html>");

        buttonGroup1.add(rdioGraphic1);
        rdioGraphic1.setText("Graphic Design");
        rdioGraphic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioGraphic1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdioMotion1);
        rdioMotion1.setText("Motion Graphics");

        buttonGroup1.add(rdioIllus1);
        rdioIllus1.setText("Illustration");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Desciption");

        jScrollPane2.setViewportView(txtArtworkDesc1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdioMotion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdioIllus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdioGraphic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdioGraphic1)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdioIllus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdioMotion1)))
                .addGap(100, 100, 100))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pneAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLogout)
                                .addGap(30, 30, 30)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblLogout)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTime)
                                .addComponent(lblDate))))
                    .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pneAdvertisement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtTargeAudinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargeAudinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargeAudinceActionPerformed

    private void rdioGraphic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioGraphic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdioGraphic1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        //TEMPORAY
        lblTotal1.setText("450");

        String cusID = lblID.getText();
        String cusName = txtName1.getText();
        String cusTP = txtTele1.getText();
        String cusEmail = txtEmail1.getText();

//        String empID = cmbEmpId.getSelectedItem().toString();

// Check if customer details are filled
        if (cusName.isEmpty() || cusTP.isEmpty() || cusEmail.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in customer details");
            return; // Exit the method if any customer detail is empty
        }

// Check if at least one order type is selected
        boolean isAdvertisementSelected = cmbObjAdv.getSelectedItem() != null && !txtTargeAudince.getText().isEmpty();
        boolean isBannerSelected = cmdBannerSize.getSelectedItem() != null && (int) spinnerQuantityBanner.getValue() > 0;
        boolean isArtworkSelected = rdioGraphic1.isSelected() || rdioIllus1.isSelected() || rdioMotion1.isSelected();

        if (!isAdvertisementSelected && !isBannerSelected && !isArtworkSelected) {
            JOptionPane.showMessageDialog(rootPane, "Please select at least one order type");
            return; // Exit the method if no order type is selected
        }
// Advertisement details
        String adObjec = "";
        String adTargetAudience = "";
        String startDate = "";
        String endDate = "";

        if (isAdvertisementSelected) {
            adObjec = cmbObjAdv.getSelectedItem().toString();
            adTargetAudience = txtTargeAudince.getText();
            String strtDyStr = txtStrtDat.getText();
            int strtMnth = strtMonth.getMonth();
            String endDyStr = txtEndDay.getText();
            int endMnth = endMonth.getMonth();

            // Validate and parse the start date
            if (strtDyStr.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in the start date");
                return; // Exit the method if start date is empty
            }
            int strtDy = Integer.parseInt(strtDyStr);

            // Validate the start date based on the selected month
            int maxDayInMonth = 31; // Maximum days in a month (default to 31)
            if (strtMnth == 3 || strtMnth == 5 || strtMnth == 8 || strtMnth == 10) {
                maxDayInMonth = 30; // Months with 30 days
            } else if (strtMnth == 1) {
                maxDayInMonth = 28; // February (assuming non-leap year)
            }

            if (strtDy < 1 || strtDy > maxDayInMonth) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid start day for the selected month");
                return; // Exit the method if start day is invalid
            }

            startDate = strtDy + " - " + strtMnth;

            // Validate and parse the end date
            if (endDyStr.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in the end date");
                return; // Exit the method if end date is empty
            }
            int endDy = Integer.parseInt(endDyStr);

            // Validate the end date based on the selected month
            maxDayInMonth = 31; // Maximum days in a month (default to 31)
            if (endMnth == 3 || endMnth == 5 || endMnth == 8 || endMnth == 10) {
                maxDayInMonth = 30; // Months with 30 days
            } else if (endMnth == 1) {
                maxDayInMonth = 28; // February (assuming non-leap year)
            }

            if (endDy < 1 || endDy > maxDayInMonth) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid end day for the selected month");
                return; // Exit the method if end day is invalid
            }

            endDate = endDy + " - " + endMnth;

            // Check if any advertisement detail is empty
            if (adObjec.isEmpty() || adTargetAudience.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in all advertisement details");
                return; // Exit the method if any advertisement detail is empty
            }
        }

// Banner details
        String bannerSize = "";
        int banQuantity = 0;
        String bannerDesc = "";

        if (isBannerSelected) {
            bannerSize = cmdBannerSize.getSelectedItem().toString();
            banQuantity = (int) spinnerQuantityBanner.getValue();
            bannerDesc = txtBannerDesc.getText();

            // Check if any banner detail is empty
            if (bannerSize.isEmpty() || bannerDesc.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in all banner details");
                return; // Exit the method if any banner detail is empty
            }
        }

// Artwork details
        String artworkType = "";
        String artworkDesc = "";

        if (isArtworkSelected) {
            if (rdioGraphic1.isSelected()) {
                artworkType = "Graphic Design";
            } else if (rdioIllus1.isSelected()) {
                artworkType = "Illustration";
            } else if (rdioMotion1.isSelected()) {
                artworkType = "Motion Graphics";
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please select an Artwork Type");
                return; // Exit the method if artwork type is not selected
            }
            artworkDesc = txtArtworkDesc1.getText();

            // Check if any artwork detail is empty
            if (artworkDesc.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in artwork description");
                return; // Exit the method if artwork description is empty
            }
        }

        double totPrice = Double.parseDouble(lblTotal1.getText());

        try {
            String query = "UPDATE orders SET CustomerName = '" + cusName + "', CustomerTelephone = '" + cusTP + "', CustomerEmail = '" + cusEmail + "', AdObjective = '" + adObjec + "', AdTargetAudience = '" + adTargetAudience + "', StartDate = '" + startDate + "', EndDate = '" + endDate + "', BannerSize = '" + bannerSize + "', Quantity = " + banQuantity + ", BannerDescription = '" + bannerDesc + "', ArtworkType = '" + artworkType + "', ArtworkDescription = '" + artworkDesc + "', TotalPrice = " + totPrice + " WHERE OrderID = " + cusID;
//            String query2 = "UPDATE employee SET status = 'Occupied' WHERE empID = " + empID;

//            statement.executeUpdate(query2);

            int rowsUpdated = statement.executeUpdate(query);
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data updated successfully in the table.");
                model.setRowCount(0);
                fetchDataFromDB();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed to update data in the table.");
            }
        } catch (SQLException sqlex) {
            JOptionPane.showMessageDialog(rootPane, sqlex);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    private void txtTele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTele1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTele1ActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void tblRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblReg.getSelectedRow();

        lblID.setText(model.getValueAt(selectedRow, 0).toString());
        txtName1.setText(tblReg.getValueAt(tblReg.getSelectedRow(), 1).toString());
        txtTele1.setText(tblReg.getValueAt(tblReg.getSelectedRow(), 2).toString());
        txtEmail1.setText(tblReg.getValueAt(tblReg.getSelectedRow(), 3).toString());

        String objValue = tblReg.getValueAt(tblReg.getSelectedRow(), 5).toString();

        int cmbObjIndex;
        switch (objValue) {
            case "Awareness":
                cmbObjIndex = 0;
                break;
            case "Marketing":
                cmbObjIndex = 1;
                break;
            case "Charity":
                cmbObjIndex = 2;
                break;
            default:
                cmbObjIndex = 0; // Set a default index if the value doesn't match any case
        }

        cmbObjAdv.setSelectedIndex(cmbObjIndex);

        txtTargeAudince.setText(model.getValueAt(selectedRow, 6).toString());

        // Get the values from the table
        String startDateValue = tblReg.getValueAt(tblReg.getSelectedRow(), 7).toString();
        String endDateValue = tblReg.getValueAt(tblReg.getSelectedRow(), 8).toString();

        if (!startDateValue.equals("") || !endDateValue.equals("")) {
// Split the start date value into day and month
            String[] startDateParts = startDateValue.split(" - ");
            String strtDyStr = startDateParts[0];
            int strtMnth = Integer.parseInt(startDateParts[1]);

// Split the end date value into day and month
            String[] endDateParts = endDateValue.split(" - ");
            String endDyStr = endDateParts[0];
            int endMnth = Integer.parseInt(endDateParts[1]);

// Set the values to the corresponding fields
            txtStrtDat.setText(strtDyStr);
            strtMonth.setMonth(strtMnth - 1); // Assuming month indices start from 1
            txtEndDay.setText(endDyStr);
            endMonth.setMonth(endMnth - 1); // Assuming month indices start from 1
        } else {
            txtStrtDat.setText("");
            txtEndDay.setText("");
        }
        String res = model.getValueAt(selectedRow, 12).toString();

        switch (res) {
            case "Graphic Design":
                rdioGraphic1.setSelected(true);
                break;
            case "Illustration":
                rdioIllus1.setSelected(true);
                break;
            case "Motion Graphics":
                rdioMotion1.setSelected(true);
                break;
        }
        txtArtworkDesc1.setText(model.getValueAt(selectedRow, 13).toString());

        String banSize = tblReg.getValueAt(selectedRow, 9).toString();

        int bannerSizeIndex = 0;
        switch (banSize) {
            case "1024*780":
                bannerSizeIndex = 0;
                break;
            case "1280*1980":
                bannerSizeIndex = 1;
                break;
            case "540*480":
                bannerSizeIndex = 2;
                break;
        }
        cmdBannerSize.setSelectedIndex(bannerSizeIndex);

        spinnerQuantityBanner.setValue(model.getValueAt(selectedRow, 10));
        txtBannerDesc.setText(model.getValueAt(selectedRow, 11).toString());


    }//GEN-LAST:event_tblRegMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String cusID = lblID.getText();
        try {
            String queryDelete = "DELETE FROM orders WHERE OrderID = " + cusID;
            statement.executeUpdate(queryDelete);
            JOptionPane.showMessageDialog(rootPane, "record deleted");
            model.setRowCount(0);
            fetchDataFromDB();
        } catch (SQLException exsql) {
            JOptionPane.showMessageDialog(rootPane, exsql);
        }
        // Reset the components to empty values
        lblID.setText("");
        txtName1.setText("");
        txtTele1.setText("");
        txtEmail1.setText("");
        cmbObjAdv.setSelectedIndex(0); // Set the default index for the combo box
        txtTargeAudince.setText("");
        txtStrtDat.setText("");
        txtEndDay.setText("");
        strtMonth.setMonth(0); // Set the default month index
        endMonth.setMonth(0); // Set the default month index
        rdioGraphic1.setSelected(false);
        rdioIllus1.setSelected(false);
        rdioMotion1.setSelected(false);
        txtArtworkDesc1.setText("");
        cmdBannerSize.setSelectedIndex(0); // Set the default index for the combo box
        spinnerQuantityBanner.setValue(0);
        txtBannerDesc.setText("");

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        EmployeeLogIn employeeLogIn = new EmployeeLogIn();
        employeeLogIn.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderRegistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderRegistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderRegistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderRegistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateOrderRegistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbObjAdv;
    private javax.swing.JComboBox<String> cmdBannerSize;
    private com.toedter.calendar.JMonthChooser endMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblTele1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblemp1;
    private javax.swing.JLabel lblheading;
    private javax.swing.JPanel pneAdvertisement;
    private javax.swing.JRadioButton rdioGraphic1;
    private javax.swing.JRadioButton rdioIllus1;
    private javax.swing.JRadioButton rdioMotion1;
    private javax.swing.JSpinner spinnerQuantityBanner;
    private com.toedter.calendar.JMonthChooser strtMonth;
    private javax.swing.JTable tblReg;
    private javax.swing.JTextPane txtArtworkDesc1;
    private javax.swing.JTextField txtBannerDesc;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEndDay;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtStrtDat;
    private javax.swing.JTextField txtTargeAudince;
    private javax.swing.JTextField txtTele1;
    // End of variables declaration//GEN-END:variables
}
